// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBinLzQZ7JKQwoKUW8_IA3Hm4ingxEjRk0',
    appId: '1:449372029041:web:724cb09635248c10dc1bd0',
    messagingSenderId: '449372029041',
    projectId: 'my-app-aa6fa',
    authDomain: 'my-app-aa6fa.firebaseapp.com',
    storageBucket: 'my-app-aa6fa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLK62T2dG5aqOonA-5o2KNvLrA0ss44OE',
    appId: '1:449372029041:android:f536a296ce572561dc1bd0',
    messagingSenderId: '449372029041',
    projectId: 'my-app-aa6fa',
    storageBucket: 'my-app-aa6fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjWhduLBJUOmRHVbzA9LSnEQZsQzRpAuk',
    appId: '1:449372029041:ios:62298cc68d31f65bdc1bd0',
    messagingSenderId: '449372029041',
    projectId: 'my-app-aa6fa',
    storageBucket: 'my-app-aa6fa.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjWhduLBJUOmRHVbzA9LSnEQZsQzRpAuk',
    appId: '1:449372029041:ios:2990d3501ff95049dc1bd0',
    messagingSenderId: '449372029041',
    projectId: 'my-app-aa6fa',
    storageBucket: 'my-app-aa6fa.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
